language: ruby
rvm:
  - 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: ChOqKv29yMCxJbPADEnbS3M8Jit4iIJpSWB38l7O0KVYZK1rwG7LOBaWdO8jOlsFBo37kcQymxPOlMi+UsywTlCx6LSazUv6SmqUeNlJUZJaKMUCnCKl5jA/zhdqHjplKDqWqsK9LzPmvLRupLlC5uiI43vjldiK3fYqXgXJu08KGdbOge3O+Sq9EGfer05cOU/6ceZjaW4dUt6zU/Hql0CPi9LiyJVx9cOECp7u60sBZ12kegV/7YR1qPuD2Adu0RKjpsPhwTMZAwQT8jgwtB0dPzgDpojGgGwWzX2sED7annbLkIJ6sdDmqyuDNE68nPtdWGQo7K5SS0LBk4VMN5smUAhipzuWM634dm/3r1rPW/CNG/HAY1s9yaCzFu1PkA1I4cKYfFvgy5mOZLkvEz8h63puLbpi3k5x6V2iQ6zvXmo7dKoIlYNFUzNTzjMh2KJfSTDj3CsKpWDywCpLeVYqnKge47Ji6mv/on/oWim3MVcbuLZ90krzivYOni3NxpKS3Ac7XN4I4wJI1GiUm18tryACZm9Wcme735V23+d8hFBJNZTZWxT63FWwkN6dOC1B33UlR10q+mhxPlSd5WCC4F8MadHcO8DpTpnKn+ou9FG0duTC30YHALzKLECjA7DXPZBI7+2HveE2HXAh7VYgcZhxe/z7Qm2ALVwdZAY=
  app: infinite-river-1447
  on:
    branch: master
    repo: AIIT-2015PBL-TeamPractice/as_backend
  run:
    - 'npm install -g bower grunt-cli'
    - 'cd client'
    - 'bower install'
    - 'grunt'
    - 'rake db:migrate'
notifications:
  slack:
    secure: MxrFE7xYqFFiFJ0Fax4DMewQt/ynjp3mN1rmpHoTz8CHBjqZUFVkbwS7bm3lm7dcVrLqWj/1bbSwZlW+M5/JddbOtNtlCpO9ELg8yenO7xqNai+PuIJHVi1nchEtBJoeN2CQEzYZKiD17qaVPohUbCyQr9CTtChy4BWOHh0ck2nalXDqlgEa977fjX1IjvFDSuYu+PEVL9a2BoBH70l7A0Nwqt7EP0wP9xbnNVLzHPkYL71KOcyhEG7wr4da/4o3aE6nn0lYelceASCwamKEGWSkq/RK3SSOPp48K4xEV/QwJIgXXk1VtoB90bq4yB612CHsQrSTOP5SXFAE5E0rs7sp5k2H5bvJK52C5tf88eBfOUDUYe034p96ZP18OMjrqT1IWc/WOIgCHtcaZuDuvuXBgEXYOebr1UA1nfvpeXIzjlsLRTcgnr8lX7QQuEE1kOKMBfGWjz7C5BMJx6AbTzJdCjT7gMC506bROgjB9IWVBoYJLnSbhG9L8hxcTTufMJtuR6XbIydMOnG2hyrW1qJmfbT80wDDutn7xcPeeGlvLX+qlG6HU99NWpVG0sDt2fY5sPR1H3HO3FBUe18z3sDxGVmUUK/n4kQImvL5EzqRyu4gOmzDOwnUFtkohW6UsAc78MS4uACdmMln5iLcrT8TQgll+MLGOT3+KR4A1L4=
