language: ruby
rvm:
- 2.2.2
bundler_args: "--without development production"
before_install:
- gem update --system
- gem --version
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: jNkUDqemcYAeiohdo/Qn0PjyFdptSz2Ae44tlONK6G8dTf+kZG8ujadP4E2t+7b7af9V1wIPXu2FengP0gVHmeM2MbBz3iN5S9Jp4ojQf/BBRc1R9YDLrhR1S2oTDrZx0spSMGTFIksb4UZSrCQEWPLGRyZvsBIQWo3OeZs6dveTPMcHCnS8qchYLMqqFBU6SAG4iGilnSDqcbhucttEpAwPQu/Ojz6596VrcwaBocAn+r4vY/IGIoqKAoodboy9rx0n+H7Y1Jvl6ml2xjy9xbN9LcKBotWRKzRRC9GUnHIiyhITe9+f8uiZYucgA+9gEJsKxlhX9aqWvhnlEOqdlsCu6YFXTdmYlp5MHJsRRkKu7M5G1JEtcwAXojkWXh2RWuHpKKHrF0e5Pnvw6GQ6MDMn59TVxdv57ooyo3Ms2PWKA+BSYreF4DVbnMTbEBjMRssIIgRWkrRbpRfndtpfaWc/lwbx8xNiWenDPnmA9SzGRC5wJGYZz7TzLzjSyCyEqHMrJmhrqA0U22EU614Nz0DJLB3GdFhfc6yJYtc8MSm1H2JoiQyZwfG3txg5vtnNcs/J+Jv7Iv/IR4abUq0ez1COw86VIyE3gp05bVEuUmW6kOhNYxJgWR/sDLPlyI0ZcUP1EInFzLuY/Xj0TIbCshyrU4WUTxE55bEy/3NT9Uk=
  app: ootalkbackend
  on:
    repo: SBR2015/OoTalk_backend
    branch: master
  run:
  - rake db:migrate
notifications:
  slack:
    secure: GSiZJlsXCfwJLKXg8x5Io1NJKTanjzLas+uUsljPytC9mkMKmSpbX4UuSUrddfpxfjVlSIMCLe/NCoYl8VUD+Knu+1TQQKGO0QSYq6cZwyIETjGb0sDs1uHs8izl5n+hJ9SqnpPUpwYvidCkzcwjHg2Nv3abnZ4+oZ/YAovmL5skQ+ybLluxPWZPHHoCKHrbcqmXj7q4d1mAgwxgyLhQ52eXaU0Rwt6p+91zAIJX3sUCJ13eHKJgH1/v9gSGEhrZrLjGMr6WjpkPRtpEvU2hWd7inq3WnjKfNIF1lCtIKFkmq4M+vyoGVGuCiB1PBJLJcOJI2caWGckQnBGMmywXSd0Ayib1z+DRRDHZ86+wOJN7kFPUOs8a1miX9u/xN9sWrOjFvI7aCuFOjQyKxUmJa7rkYdYJ3JBJBEc/vtlf/iNV5a5cLlK/NO6d7cUa2+9Q9JksQxsrD1B13wSmBq8R+YGg8Ij9F/Jt2riZnQa1/UFKjmBAgD0IcjDF9whudsWXNwnHv8dggV9n+bEVFOvkb+2L308g271d31mZ1MKAG7351SIR1o17O0RPE8pEmTG2RdCFif48A/kS4laRAoPZ//cvfXuSYChynJsIqr1IBv9r578RD1kjEW++AMDrj09HWUsTrwVdLglDdmFsjfixlOnQ0IDaTXV2Zg14OCZNGx4=
