language: ruby
rvm:
- 2.2.3
bundler_args: "--without development production"
before_install:
- gem update --system
- gem --version
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: e9DnZmFY1Sj7QhoSGjxEwsNYY//2kHXK3DAB7XLG8HaNxnRi2cYfPKbOFnTfayLqa8RAi4W1dJfeLUQqJaMDqndWnwc0LzMFIvnKrnLoQL4bbyi240hR9rkOHWR96tXlev7w3yfVMfMFMnN3rUx8tP2iNVsJS4Y6Ck3iRfrhjnfrZ6udK9/ei7UV3zuxTHfEM3ze7IFJ+X3Iyeh1IqG1/52S9bpFedcINulxrhAjEalO7CTIVAbb5iARW0kkSD5Y1hsGNJC5T7io5DFy5JxaqCjQuM91spn2zTev+5E6GDdr2OY+P3kSLQz9OFRRi2uYqJiYSJ5VwoM8ZsuyKiSd8TbUpMPjdEYNSIT5uW/5XijA4JPFqhzJFEDMgUd/WJU+PjTvJL4+hRHbzd809lrgND3b2zdYaSAbKxtlhd5RHd8PRzvA1y1Ib3LmeI5efEpiG2TuXVJdBwlQnh6N2Wgv6m0STrmq42XOD0/gD7ZbWQBesHOrqexTlLbBT6eCOjwz+q7+UbkEP4cDFRxeCp7RikPM8MgLVKxhnWf5yYOEYTzAlAn2uqYa8t88k90mwuxR4p648rezw3u9xdmiVwpmP0I1FvcDB63/ZYmDBWHCLI8oIcZJJExh/ApjHbzmd7LFFnUQZlzgFmMCMSH1s31g5PU301419dVNaqWETAqPUoc=
  app: ootalkbackend
  on:
    repo: SBR2015/OoTalk_backend
    branch: master
  run:
  - rake db:migrate
notifications:
  slack:
    secure: GSiZJlsXCfwJLKXg8x5Io1NJKTanjzLas+uUsljPytC9mkMKmSpbX4UuSUrddfpxfjVlSIMCLe/NCoYl8VUD+Knu+1TQQKGO0QSYq6cZwyIETjGb0sDs1uHs8izl5n+hJ9SqnpPUpwYvidCkzcwjHg2Nv3abnZ4+oZ/YAovmL5skQ+ybLluxPWZPHHoCKHrbcqmXj7q4d1mAgwxgyLhQ52eXaU0Rwt6p+91zAIJX3sUCJ13eHKJgH1/v9gSGEhrZrLjGMr6WjpkPRtpEvU2hWd7inq3WnjKfNIF1lCtIKFkmq4M+vyoGVGuCiB1PBJLJcOJI2caWGckQnBGMmywXSd0Ayib1z+DRRDHZ86+wOJN7kFPUOs8a1miX9u/xN9sWrOjFvI7aCuFOjQyKxUmJa7rkYdYJ3JBJBEc/vtlf/iNV5a5cLlK/NO6d7cUa2+9Q9JksQxsrD1B13wSmBq8R+YGg8Ij9F/Jt2riZnQa1/UFKjmBAgD0IcjDF9whudsWXNwnHv8dggV9n+bEVFOvkb+2L308g271d31mZ1MKAG7351SIR1o17O0RPE8pEmTG2RdCFif48A/kS4laRAoPZ//cvfXuSYChynJsIqr1IBv9r578RD1kjEW++AMDrj09HWUsTrwVdLglDdmFsjfixlOnQ0IDaTXV2Zg14OCZNGx4=
